### new
dpo:
  rng_seed: 0xa1221f97
  is_reward_model: false
  dpo_beta: 0.1
  learning_rate: 1e-5
  gradient_checkpointing: false
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-12
  weight_decay: 0.00
  warmup_steps: 10
  eval_steps: 50
  save_steps: 100
  save_strategy: steps
  max_length: 512
  num_train_epochs: 2
  logging_steps: 10
  max_grad_norm: 2.0
  save_total_limit: 10
  dtype: fp16
  eval_accumulation_steps:
  freeze_layer:
  datasets:
    - anthropic_rlhf
    - shp
    - hellaswag
    - webgpt:
        val_split: 0.2
    - hf_summary_pairs
    - oasst_export
  datasets_extra: [] # For config options to add additional datasets, since yaml doesn't let us extend arrays
  cache_dir: .cache
  loss_fn: RMLoss
  score_l2_reg: 0.001
  eval_size:
  log_dir: "base"
  quantization: false
  seq2seqmodel: false
  fuse_gelu: true
  log_wandb: true
  verbose: true
  # use_custom_sampler: false
  residual_dropout: 0.0
  use_flash_attention: false
  sort_by_length: false
  per_digit_tokens: false
  datasets_extra: []
  metrics: ["accuracy"]
  deepspeed_config: configs/zero_config.json
  max_replies: 5
  residual_dropout_lima: false
  use_system_tag: false
  system_property_dropout: 0.5
  system_add_length: false
  peft_model: false
  peft_type: "lora"


###############################################
# Model and Dataset Configs
###############################################


### new
llama2-7b-dpo:
  is_reward_model: false
  datasets:
    - anthropic_rlhf:
        max_val_set: 1000
    - shp:
        max_val_set: 1000
    - hellaswag:
        max_val_set: 1000
    - webgpt:
        val_split: 0.2
        max_val_set: 1000
    - hf_summary_pairs:
        max_val_set: 1000
    - oasst_export:
        max_val_set: 1000
  sort_by_length: false
  # use_custom_sampler: true
  # model_name: "meta-llama/Llama-2-7b-hf"
  model_name: /root/haikang/Open-Assistant-hfa/lhf/saved_models/lm-sft/llama2-7b/checkpoint-10000
  output_dir: /root/haikang/Open-Assistant-hfa/lhf/saved_models/dpo/llama2-7b
  dpo_beta: 0.1
  learning_rate: 5e-6
  residual_dropout: 0.0
  weight_decay: 0.0
  max_length: 4096
  use_flash_attention: true
  gradient_checkpointing: true
  warmup_steps: 1000
  dtype: bf16
  gradient_accumulation_steps: 1
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 1
  eval_steps: 1000
  save_steps: 2000
  deepspeed_config: configs/zero3_config_sft.json
  use_system_tag: false
  system_property_dropout: 0.5
  system_add_length: false
  verbose: True
  patch_unsupported: True